/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Inspection } from "./Inspection";
import { InspectionCountArgs } from "./InspectionCountArgs";
import { InspectionFindManyArgs } from "./InspectionFindManyArgs";
import { InspectionFindUniqueArgs } from "./InspectionFindUniqueArgs";
import { DeleteInspectionArgs } from "./DeleteInspectionArgs";
import { InspectionService } from "../inspection.service";
@graphql.Resolver(() => Inspection)
export class InspectionResolverBase {
  constructor(protected readonly service: InspectionService) {}

  async _inspectionsMeta(
    @graphql.Args() args: InspectionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Inspection])
  async inspections(
    @graphql.Args() args: InspectionFindManyArgs
  ): Promise<Inspection[]> {
    return this.service.inspections(args);
  }

  @graphql.Query(() => Inspection, { nullable: true })
  async inspection(
    @graphql.Args() args: InspectionFindUniqueArgs
  ): Promise<Inspection | null> {
    const result = await this.service.inspection(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Inspection)
  async deleteInspection(
    @graphql.Args() args: DeleteInspectionArgs
  ): Promise<Inspection | null> {
    try {
      return await this.service.deleteInspection(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
